/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package geneadmin;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.logging.*;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Hosenilla
 */
public class EditAncestor extends javax.swing.JFrame {
File f = null; 
String path = null;
private ImageIcon format =null;
String imgname = null;
int a = 0; 
byte[] pimage = null; 
PreparedStatement ps;
ResultSet rs;
private static int tempoid;
private static byte[] testb;

private static String fname;
private static String lname;
private static String mname;
private static String gender;
private static String dth;
private static String age;
private static String date;

    /**
     * Creates new form EditAncestor
     */
    public EditAncestor() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMale);
        bg.add(jRadioButtonFemale);
        
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(radiono);
        bg2.add(radioyes);
        loadtest();
    }
    public EditAncestor(int forid){
    
    PreparedStatement st;
        ResultSet rs;
        String query = "SELECT * FROM `ancestor_tb` WHERE `id` = ?";
       
        try {
            st = geneadmin.connect.getConnection().prepareStatement(query);    
            st.setInt(1, forid);
            rs = st.executeQuery();              
            if(rs.next()){
                tempoid = forid;
                fname = rs.getString("firstname");
                lname = rs.getString("lastname");
                mname = rs.getString("middlename");
                gender = rs.getString("gender");
                dth = rs.getString("death");
                age = rs.getString("age");
                date = rs.getString("birthdate");
                
                
                   
            }else{
                //error message
                JOptionPane.showMessageDialog(null, "Login Error","Login Error", 2);         
            }    
        } catch (SQLException ex) {
            Logger.getLogger(geneadmin.LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public void loadtest(){
    PreparedStatement st;
        ResultSet rs;
        String query = "SELECT * FROM `ancestor_tb` WHERE `id` = ?";
       
        try {
            st = geneadmin.connect.getConnection().prepareStatement(query);    
            st.setInt(1, tempoid);
            rs = st.executeQuery();              
            if(rs.next()){
                
                
        byte[] imagedata = rs.getBytes("imgfile");
        format = new ImageIcon(imagedata);
        Image mm = format.getImage();
        Image img2 = mm.getScaledInstance(200,200, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        labelimage.setIcon(image);
        
        jfname.setText(fname);
        jlname.setText(lname);
        jmname.setText(mname);
        jage.setText(age);
        java.util.Date date2;
                try {
                    date2 = new SimpleDateFormat("yyyy-MM-dd").parse(date);
                    jDateChooser1.setDate(date2);
                } catch (ParseException ex) {
                    Logger.getLogger(EditAncestor.class.getName()).log(Level.SEVERE, null, ex);
                }
                
         if(gender.equals("Male")){
         jRadioButtonMale.setSelected(true);
         }else{
         jRadioButtonFemale.setSelected(true);
         }
         if(dth.equals("Deceased")){
         radioyes.setSelected(true);
         }else{
         radiono.setSelected(true);
         }
        
        
        
            
            }else{
                //error message
                JOptionPane.showMessageDialog(null, "Login Error","Login Error", 2);         
            }    
        } catch (SQLException ex) {
            Logger.getLogger(geneadmin.LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelimage = new javax.swing.JLabel();
        imagepath = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jfname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jlname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jmname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jage = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        radiono = new javax.swing.JRadioButton();
        radioyes = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        getContentPane().add(labelimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 200, 181));

        imagepath.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(imagepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 234, 33));

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 80, 20));

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Save Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 110, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(840, 80));

        jLabel8.setBackground(new java.awt.Color(153, 255, 153));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("EDIT ANCESTOR");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 153, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geneadmin/icons8-back-30.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Currently Editing:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText(fname+" "+lname +" ID # "+tempoid);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 80));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("First Name");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jfname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jfname.setPreferredSize(new java.awt.Dimension(59, 26));
        jfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfnameActionPerformed(evt);
            }
        });
        getContentPane().add(jfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Last Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jlname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlname.setPreferredSize(new java.awt.Dimension(59, 26));
        jlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlnameActionPerformed(evt);
            }
        });
        getContentPane().add(jlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Middle Name");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jmname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jmname.setPreferredSize(new java.awt.Dimension(59, 26));
        jmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnameActionPerformed(evt);
            }
        });
        getContentPane().add(jmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Age");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jage.setPreferredSize(new java.awt.Dimension(59, 26));
        jage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jageActionPerformed(evt);
            }
        });
        getContentPane().add(jage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 80, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Birth Date");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 160, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Gender");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jRadioButtonMale.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jRadioButtonFemale.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButtonFemale.setText("Female");
        getContentPane().add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Status");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        radiono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radiono.setText("Alive");
        radiono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionoActionPerformed(evt);
            }
        });
        getContentPane().add(radiono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        radioyes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radioyes.setText("Deceased");
        radioyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioyesActionPerformed(evt);
            }
        });
        getContentPane().add(radioyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("Save Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed

        JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG","png","jpeg","jpg");
        filechooser.addChoosableFileFilter(fnwf);
        int load = filechooser.showOpenDialog(null);

        if(load==filechooser.APPROVE_OPTION){
            f = filechooser.getSelectedFile();

            path = f.getAbsolutePath();
            imagepath.setText(path);
            ImageIcon ii = new ImageIcon(path);
            Image img = ii.getImage().getScaledInstance(200,200, Image.SCALE_SMOOTH);
            labelimage.setIcon( new ImageIcon(img));

        }
    }//GEN-LAST:event_browseActionPerformed

    private void jfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfnameActionPerformed

    private void jlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlnameActionPerformed

    }//GEN-LAST:event_jlnameActionPerformed

    private void jmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnameActionPerformed

    private void jageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jageActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void radionoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radionoActionPerformed

    private void radioyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioyesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String fname1 = jfname.getText();
        String lname1 = jlname.getText();
        String mname1 = jmname.getText();
        String death1 = "Alive";
        if(radioyes.isSelected())
        {
            death1 = "Deceased";
        }
        String gender1 = "Male";
        if(jRadioButtonFemale.isSelected())
        {
            gender1 = "Female";
        }
        String age1 = jage.getText();
        
        String queryfind = "UPDATE ancestor_tb SET firstname = ?, lastname = ?, middlename= ?, gender = ?, death = ?, age = ?, birthdate = ? WHERE id=?";
        // "INSERT INTO `ancestor_tb`(`firstname`, `lastname`, `middlename`, `gender`, `death`, `age`, `birthdate`, `imgfile`) VALUES (?,?,?,?,?,?,?,?)";
           
          
            try{
            
            ps = connect.getConnection().prepareStatement(queryfind);
            ps.setString(1, fname1);
            ps.setString(2, lname1);
            ps.setString(3, mname1);
            ps.setString(4, gender1);
            ps.setString(5, death1);
            ps.setString(6, age1);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jDateChooser1.getDate());
            ps.setString(7, date); 
            ps.setInt(8, tempoid);
            ps.executeUpdate();
            if(ps.executeUpdate() != 0){
                JOptionPane.showMessageDialog(null, "Ancestor Has Been Updated");
                
            }else{
                JOptionPane.showMessageDialog(null, "Error");
            } 
            
            
            }catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            } 
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        String queryfind = "UPDATE ancestor_tb SET imgfile = ? WHERE id = ?";
        try{
        InputStream is = new FileInputStream(f);
        ps = connect.getConnection().prepareStatement(queryfind);  
        ps.setBlob(1, is);
        ps.setInt(2, tempoid);
        ps.executeUpdate();
       
        
        
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error");
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error");
        Logger.getLogger(AddAncestor.class.getName()).log(Level.SEVERE, null, ex);
        
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAncestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAncestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAncestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAncestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAncestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JTextField imagepath;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jage;
    private javax.swing.JTextField jfname;
    private javax.swing.JTextField jlname;
    private javax.swing.JTextField jmname;
    private javax.swing.JLabel labelimage;
    private javax.swing.JRadioButton radiono;
    private javax.swing.JRadioButton radioyes;
    // End of variables declaration//GEN-END:variables
}
